### ISSUE TITLE
Zaak betalingsindicatie is not being translated

### ISSUE THREAD

**Issue by MLenterman** [wearefrank/zaakbrug#268]
Currently we dont see any errors, because an empty string betalingsindicatie is valid in ZGW. We need to add translations for betalingsindicatie from ZDS -> ZGW and back from ZGW -> ZDS in all relevant zaak translations.

- [ ] Create translation betalingsindicatie ZDS -> ZGW
- [ ] Create translation betalingsindicatie ZGW -> ZDS
- [ ] Create tests for betalingsindicatie. Needs to cover creeerZaak, updateZaak without betalingsindicatie changing, updateZaak with betalingsindicatie changing and geefZaakDetails.
- [ ] Add translations to all relevant zaak transformations

ZDS enum:
```xml
<simpleType name="BetalingsIndicatie">
	<restriction base="string">
		<enumeration value="N.v.t."/>
		<enumeration value="(Nog) niet"/>
		<enumeration value="Gedeeltelijk"/>
		<enumeration value="Geheel"/>
	</restriction>
</simpleType>
```

ZGW enum:
```yaml
BetalingsindicatieEnum:
      enum:
        - nvt
        - nog_niet
        - gedeeltelijk
        - geheel
      type: string
    BlankEnum:
      enum:
        - ''
```
